# Generated by Django 3.2.6 on 2021-08-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_upload_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
